"""empty message

Revision ID: 1d5b3da9dc26
Revises: 471c9e76701
Create Date: 2016-06-02 08:54:45.824000

"""

# revision identifiers, used by Alembic.
revision = '1d5b3da9dc26'
down_revision = '471c9e76701'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
