"""empty message

Revision ID: 471c9e76701
Revises: 49805d2efc7
Create Date: 2016-06-01 00:33:11.362688

"""

# revision identifiers, used by Alembic.
revision = '471c9e76701'
down_revision = '49805d2efc7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('our_iban', sa.String(length=25), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('bic_blz', sa.String(length=25), nullable=True),
    sa.Column('transaction_number', sa.String(length=25), nullable=True),
    sa.Column('iban_knr', sa.String(length=25), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    ### end Alembic commands ###
