"""empty message

Revision ID: 49805d2efc7
Revises: 32fd1ea00aa
Create Date: 2016-05-27 00:10:43.003047

"""

# revision identifiers, used by Alembic.
revision = '49805d2efc7'
down_revision = '32fd1ea00aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_meta', sa.Column('surname', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_meta', 'surname')
    ### end Alembic commands ###
